SisUnimed/Controllers/MateriaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisUnimed.Models;

namespace SisUnimed.Controllers
{
    public class MateriaisController : Controller
    {
        //
        // GET: /Materiais/

        public ActionResult Materiais()
        {
            if (Session["usuariologadoId"] != null)
            {
                using (UnimedEntities1 up = new UnimedEntities1())
                {
                    int usuario_id = int.Parse(Session["usuariologadoId"].ToString());
                    var resultado = up.usuario_permissao.Where(a => a.id_usuario.Equals(usuario_id)).FirstOrDefault();

                    ViewData["usuario_permissao"] = resultado;

                    // busca fornecedores na tabela
                    var materiais = from a in up.materiais
                                    join b in up.usuarios on a.sisusuarioi equals b.id into g
                                    join c in up.usuarios on a.sisusuarioa equals c.id into h
                                    from x in g.DefaultIfEmpty()
                                    from y in h.DefaultIfEmpty()
                                    select new ListaMaterial
                                    {
                                        id = a.id,
                                        c_cod_ref_fabr = a.c_cod_ref_fabr,
                                        c_codigo_tuss = a.c_codigo_tuss,
                                        c_composicao = a.c_composicao,
                                        c_descricao_generica = a.c_descricao_generica,
                                        c_justificativa_alteracao = a.c_justificativa_alteracao,
                                        c_nome_comercial = a.c_nome_comercial,
                                        c_nome_material = a.c_nome_material,
                                        c_registro_anvisa = a.c_registro_anvisa,
                                        c_tnumm = a.c_tnumm,
                                        classificacao = a.classificaco.c_descricao,
                                        d_fim_vigencia = a.d_fim_vigencia,
                                        d_inicio_vigencia = a.d_inicio_vigencia,
                                        d_validade = a.d_validade,
                                        f_distribuidor_exclusivo = a.f_distribuidor_exclusivo == true ? "Sim" : "Não",
                                        f_nao_negociado = a.f_nao_negociado == true ? "Sim" : "Não",
                                        f_origem = a.f_origem == 1 ? "Nacional" : "Importado",
                                        f_status = a.f_status == 1 ? "Disponível" : "Indisponível",
                                        fornecedor = a.fornecedore.c_razao_social,
                                        marca = a.marca1.c_nome,
                                        v_preco = a.v_preco,
                                        unidade = a.unidade1.c_sigla,
                                        sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                        sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                        sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                        sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario)
                                    };
                    ViewData["listamaterial"] = materiais.ToList();

                    var classificacao = from a in up.classificacoes
                                        select new ListaClassificacao
                                        {
                                            id = a.id,
                                            descricao = a.c_descricao
                                        };

                    ViewData["listaclassificacao"] = classificacao.ToList();

                    var fornecedor = from a in up.fornecedores
                                     select new ListaFornecedor
                                     {
                                         c_razao_social = a.c_razao_social,
                                         id = a.id
                                     };
                    ViewData["listafornecedor"] = fornecedor.ToList();

                    var marca = from a in up.marcas
                                select new ListaMarca
                                {
                                    c_nome = a.c_nome,
                                    id = a.id
                                };
                    ViewData["listamarca"] = marca.ToList();

                    var unidade = from a in up.unidades
                                  select new ListaUnidade
                                  {
                                      c_sigla = a.c_sigla,
                                      id = a.id
                                  };
                    ViewData["listaunidade"] = unidade.ToList();

                    //lista informacao
                    var listainformacao = from a in up.materiais_informacoes
                                          join b in up.usuarios on a.sisusuarioi equals b.id into g
                                          join c in up.usuarios on a.sisusuarioa equals c.id into h
                                          from x in g.DefaultIfEmpty()
                                          from y in h.DefaultIfEmpty()
                                          where a.material == 0
                                          select new ListaMatInformacao
                                          {
                                              id = a.id,
                                              c_informacoes = a.c_informacoes,
                                              material = a.material,
                                              sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                              sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                              sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                              sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario)
                                          };
                    ViewData["listainformacao"] = listainformacao.ToList();

                    // lista procedimento
                    var listaprocedimentos = from a in up.materiais_procedimentos
                                             join b in up.usuarios on a.sisusuarioi equals b.id into g
                                             join c in up.usuarios on a.sisusuarioa equals c.id into h
                                             from x in g.DefaultIfEmpty()
                                             from y in h.DefaultIfEmpty()
                                             where a.material == 0
                                             select new ListaMatProcedimento
                                             {
                                                 id = a.id,
                                                 procedimento = a.procedimento1.c_descricao,
                                                 material = a.material,
                                                 sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                                 sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                                 sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                                 sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario)
                                             };
                    ViewData["listaprocedimentos"] = listaprocedimentos.ToList();

                    var lstprocedimento = from a in up.procedimentos
                                          select new ListaProcedimentos
                                          {
                                              id = a.id,
                                              c_codigo = a.c_codigo,
                                              c_descricao = a.c_descricao
                                          };
                    ViewData["lstprocedimento"] = lstprocedimento.ToList();

                    // lista similares
                    var listasimilares = from a in up.materiais_similares
                                         join b in up.usuarios on a.sisusuarioi equals b.id into g
                                         join c in up.usuarios on a.sisusuarioa equals c.id into h
                                         from x in g.DefaultIfEmpty()
                                         from y in h.DefaultIfEmpty()
                                         where a.material == 0
                                         select new ListaMatSimilar
                                         {
                                             id = a.id,
                                             material_similar = a.materiai1.c_nome_material,
                                             material = a.material,
                                             sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                             sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                             sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                             sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario)
                                         };
                    ViewData["listasimilares"] = listasimilares.ToList();

                    var lstmaterial = from a in up.materiais
                                      select new ListaMaterial
                                      {
                                          id = a.id,

SisUnimed/Views/Materiais/ListaInformacao.cshtml
@model IEnumerable<SisUnimed.Models.ListaMatInformacao>

@{       
    IEnumerable<SisUnimed.Models.ListaMatInformacao> listainformacao = (IEnumerable<SisUnimed.Models.ListaMatInformacao>)ViewData["listainformacao"];
    var grid = new WebGrid(listainformacao.ToList(), ajaxUpdateCallback: "divGridInformacao", ajaxUpdateContainerId: "divGridInformacao", defaultSort: "c_informacao", rowsPerPage: 5);
}


        <fieldset>
            <legend>Informações</legend>

                @grid.GetHtml(tableStyle: "table",alternatingRowStyle: "alternate", headerStyle: "header", columns: new[] {                    
                    grid.Column(columnName: "id",header:"id",format: a => new HtmlString(Ajax.ActionLink((string)a.id.ToString(),"PreencheCamposInformacao",new{id_info=a.id,id=a.material},new AjaxOptions {UpdateTargetId="cadInformacao"}).ToString()),canSort: true),
                    grid.Column(columnName: "c_informacoes",header:"Informação",format: a => new HtmlString(Ajax.ActionLink((string)a.c_informacoes.ToString(),"PreencheCamposInformacao",new{id_info=a.id,id=a.material},new AjaxOptions {UpdateTargetId="cadInformacao"}).ToString()),canSort: true),
                  
                   
                    grid.Column(columnName: "sisdatai", header: "Data de Inclusão", format: a => new HtmlString(Ajax.ActionLink((string)a.sisdatai.ToString(),"PreencheCamposInformacao", new { id_info=a.id,id=a.material},new AjaxOptions {UpdateTargetId="cadInformacao"}).ToString()),canSort: true),
                    grid.Column(columnName: "sisusuarioi", header: "Usuário Inclusão", format: a => new HtmlString(Ajax.ActionLink((string)a.sisusuarioi.ToString(),"PreencheCamposInformacao", new {id_info=a.id,id=a.material},new AjaxOptions {UpdateTargetId="cadInformacao"}).ToString()),canSort: true),
                    grid.Column(columnName: "sisdataa", header: "Última Alteração", format: a => new HtmlString(Ajax.ActionLink((string)a.sisdataa.ToString(),"PreencheCamposInformacao", new { id_info=a.id,id=a.material},new AjaxOptions {UpdateTargetId="cadInformacao"}).ToString()),canSort: true),
                    grid.Column(columnName: "sisusuarioa", header: "Usuário Alteração", format: a => new HtmlString(Ajax.ActionLink((string)a.sisusuarioa.ToString(),"PreencheCamposInformacao", new {id_info=a.id,id=a.material},new AjaxOptions {UpdateTargetId="cadInformacao"}).ToString()),canSort: true)
    
                })

        </fieldset>

SisUnimed/Views/Materiais/ListaMateriais.cshtml
@model IEnumerable<SisUnimed.Models.ListaMaterial>

@{       
    IEnumerable<SisUnimed.Models.ListaMaterial> listamaterial = (IEnumerable<SisUnimed.Models.ListaMaterial>)ViewData["listamaterial"];
    var grid = new WebGrid(listamaterial.ToList(),ajaxUpdateCallback:"divGrid",ajaxUpdateContainerId:"divGrid", defaultSort: "c_nome_material", rowsPerPage: 5);
}

<div id="divGrid">
        <fieldset>
            <legend>Materiais</legend>

                @grid.GetHtml(tableStyle: "table",alternatingRowStyle: "alternate", headerStyle: "header", columns: new[] {                    
                    grid.Column(columnName: "id",header:"Código",format: a => new HtmlString(Ajax.ActionLink((string)a.id.ToString(),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "c_nome_material",header:"Nome Material",format: a => new HtmlString(Ajax.ActionLink((string)a.c_nome_material.ToString(),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "c_nome_comercial",header:"Nome Comercial",format: a => new HtmlString(Ajax.ActionLink((string)a.c_nome_comercial.ToString(),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "classificacao",header:"Classificação",format: a => new HtmlString(Ajax.ActionLink((string)a.classificacao.ToString(),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "d_inicio_vigencia",header:"Inicio Vigência",format: a => new HtmlString(Ajax.ActionLink((string)a.d_inicio_vigencia.ToString(),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "d_fim_vigencia",header:"Fim Vigência",format: a => new HtmlString(Ajax.ActionLink((string)a.d_fim_vigencia.ToString(),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "v_preco",header:"Valor Base R$",format: a => new HtmlString(Ajax.ActionLink((string)string.Format("{0:C}",a.v_preco),"PreencheCampos",new{id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    
                    grid.Column(columnName: "sisdatai", header: "Data de Inclusão", format: a => new HtmlString(Ajax.ActionLink((string)a.sisdatai.ToString(),"PreencheCampos", new { id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "sisusuarioi", header: "Usuário Inclusão", format: a => new HtmlString(Ajax.ActionLink((string)a.sisusuarioi.ToString(),"PreencheCampos", new { id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "sisdataa", header: "Última Alteração", format: a => new HtmlString(Ajax.ActionLink((string)a.sisdataa.ToString(),"PreencheCampos", new { id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true),
                    grid.Column(columnName: "sisusuarioa", header: "Usuário Alteração", format: a => new HtmlString(Ajax.ActionLink((string)a.sisusuarioa.ToString(),"PreencheCampos", new { id=a.id},new AjaxOptions {UpdateTargetId="corposite"}).ToString()),canSort: true)
    
                })

        </fieldset>

</div>

SisUnimed/Views/Materiais/MateriaisInformacao.cshtml
@model SisUnimed.Models.vModelDetalheMateriais
@{
    
    IEnumerable<SisUnimed.Models.ListaMatInformacao> listainformacao = (IEnumerable<SisUnimed.Models.ListaMatInformacao>)ViewData["listainformacao"];
   
}      

<table class="table">
    <tr>
        @if (Model.vmateriais.id > 0)
        {
            <td width="65px"><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadInformacao" href="@Url.Action("IncluirInformacao", "Materiais", new { id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnAdd.png" /></a></td>
        }
        @if (Model.vmateriais_informacoes != null && (Model.vmateriais_informacoes.id) > 0)
        {
            <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadInformacao" href="@Url.Action("DeleteInformacao","Materiais",new {id_info = Model.vmateriais_informacoes.id, id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnExcluir.png" /></a></td>
        }
    </tr>
</table>


               
                            @using (Ajax.BeginForm((string)ViewBag.Action,"Materiais",new AjaxOptions { HttpMethod="POST",InsertionMode = InsertionMode.Replace, UpdateTargetId="cadInformacao" }, new{@id="formCadastro"}))
                            {
                                 @Html.AntiForgeryToken()
                                 @Html.ValidationSummary(true)
                                @Html.HiddenFor(a => a.vmateriais_informacoes.id)
                                @Html.HiddenFor(a => a.vmateriais_informacoes.material)
                                <table class="table">
                                 @if (@ViewBag.Message != null)
                                 {
                                     
                                     <tr>
                                         <td>
                                           
                                               @Html.Raw(ViewBag.Message)
                                            
                                         </td>
                                     </tr>
                                 }
                                <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vmateriais_informacoes.c_informacoes)</font></td>
                                                                     

                                   
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vmateriais_informacoes.c_informacoes,new{@class="txtcorposite"})</td>
                                   <td>@Html.TextAreaFor(a => a.vmateriais_informacoes.c_informacoes, new {@cols="100",@rows="5", @style="text-transform: uppercase" })</td>
                                  
                                   
                               </tr>
                                                           
                                               
                                                             
                                <tr>   
                                    @if ((ViewBag.Action == "InserirInformacao" || ViewBag.Action == "EditarInformacao") && Model.vmateriais_informacoes != null)
                                    {                                 
                                        <td><input type="image" class="btnIncluir" src="/Contents/Images/btnSalvar.png" value="submit"/></td>
                                        <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadInformacao" href="@Url.Action("Informacao", "Materiais", new { id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnCancelar.png" /></a></td>
                                    }    
                                </tr>
                             </table>
                            }  

    <table class="table">
        <tr>
            <td>
                <div id="divGridInformacao">
                    @{Html.RenderPartial("ListaInformacao",listainformacao);}
                </div>
            </td>
        </tr>
    </table>
               
                       

SisUnimed/Views/Materiais/MateriaisProcedimentos.cshtml
@model SisUnimed.Models.vModelDetalheMateriais
@{
    
    IEnumerable<SisUnimed.Models.ListaMatProcedimento> listaprocedimentos = (IEnumerable<SisUnimed.Models.ListaMatProcedimento>)ViewData["listaprocedimentos"];
    IEnumerable<SisUnimed.Models.ListaProcedimentos> lstprocedimento = (IEnumerable<SisUnimed.Models.ListaProcedimentos>)ViewData["lstprocedimento"];

    List<SelectListItem> procedimento = new List<SelectListItem>();
    
    foreach (var x in lstprocedimento)
    {
        procedimento.Add(new SelectListItem { 
            Text = x.c_descricao + " - " + x.c_codigo,
            Value = x.id.ToString()
        });
    };
   
}  
    

<table class="table">
    <tr>
        @if (Model.vmateriais.id > 0)
        {
            <td width="65px"><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadProcedimento" href="@Url.Action("IncluirProcedimento", "Materiais", new { id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnAdd.png" /></a></td>
        }
        @if (Model.vmateriais_procedimentos != null && (Model.vmateriais_procedimentos.id) > 0)
        {
            <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadProcedimento" href="@Url.Action("DeleteProcedimento","Materiais",new {id_proc = Model.vmateriais_procedimentos.id, id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnExcluir.png" /></a></td>
        }
    </tr>
</table>


               
                            @using (Ajax.BeginForm((string)ViewBag.Action,"Materiais",new AjaxOptions { HttpMethod="POST",InsertionMode = InsertionMode.Replace, UpdateTargetId="cadProcedimento" }, new{@id="formCadastro"}))
                            {
                                 @Html.AntiForgeryToken()
                                 @Html.ValidationSummary(true)
                                @Html.HiddenFor(a => a.vmateriais_procedimentos.id)
                                @Html.HiddenFor(a => a.vmateriais_procedimentos.material)
                                <table class="table">
                                 @if (@ViewBag.Message != null)
                                 {
                                     
                                     <tr>
                                         <td>
                                           
                                               @Html.Raw(ViewBag.Message)
                                            
                                         </td>
                                     </tr>
                                 }
                                <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vmateriais_procedimentos.procedimento)</font></td>
                                                                     

                                   
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vmateriais_procedimentos.procedimento,new{@class="txtcorposite"})</td>
                                   <td>@Html.DropDownListFor(a => a.vmateriais_procedimentos.procedimento,procedimento)</td>
                                  
                                   
                               </tr>
                                                           
                                               
                                                             
                                <tr>   
                                    @if ((ViewBag.Action == "InserirProcedimento" || ViewBag.Action == "EditarProcedimento") && Model.vmateriais_procedimentos != null)
                                    {                                 
                                        <td><input type="image" class="btnIncluir" src="/Contents/Images/btnSalvar.png" value="submit"/></td>
                                        <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadProcedimento" href="@Url.Action("Procedimento", "Materiais", new { id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnCancelar.png" /></a></td>
                                    }    
                                </tr>
                             </table>
                            }  

    <table class="table">
        <tr>
            <td>
                <div id="divGridProcedimento">
                    @{Html.RenderPartial("ListaProcedimento",listaprocedimentos);}
                </div>
            </td>
        </tr>
    </table>
               
                       

SisUnimed/Views/Materiais/MateriaisSimilares.cshtml
@model SisUnimed.Models.vModelDetalheMateriais
@{
    
    IEnumerable<SisUnimed.Models.ListaMatSimilar> listasimilares = (IEnumerable<SisUnimed.Models.ListaMatSimilar>)ViewData["listasimilares"];
    IEnumerable<SisUnimed.Models.ListaMaterial> lstMaterial = (IEnumerable<SisUnimed.Models.ListaMaterial>)ViewData["lstmaterial"];

    List<SelectListItem> material = new List<SelectListItem>();
    
    foreach (var x in lstMaterial)
    {
        material.Add(new SelectListItem { 
            Text = x.c_nome_material,
            Value = x.id.ToString()
        });
    };
   
}  
    

<table class="table">
    <tr>
        @if (Model.vmateriais.id > 0)
        {
            <td width="65px"><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadSimilares" href="@Url.Action("IncluirSimilar", "Materiais", new { id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnAdd.png" /></a></td>
        }
        @if (Model.vmateriais_similares != null && (Model.vmateriais_similares.id) > 0)
        {
            <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadSimilares" href="@Url.Action("DeleteSimilar","Materiais",new {id_similar = Model.vmateriais_similares.id, id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnExcluir.png" /></a></td>
        }
    </tr>
</table>


               
                            @using (Ajax.BeginForm((string)ViewBag.Action,"Materiais",new AjaxOptions { HttpMethod="POST",InsertionMode = InsertionMode.Replace, UpdateTargetId="cadSimilares" }, new{@id="formCadastro"}))
                            {
                                 @Html.AntiForgeryToken()
                                 @Html.ValidationSummary(true)
                                @Html.HiddenFor(a => a.vmateriais_similares.id)
                                @Html.HiddenFor(a => a.vmateriais_similares.material)
                                <table class="table">
                                 @if (@ViewBag.Message != null)
                                 {
                                     
                                     <tr>
                                         <td>
                                           
                                               @Html.Raw(ViewBag.Message)
                                            
                                         </td>
                                     </tr>
                                 }
                                <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vmateriais_similares.material_similar)</font></td>
                                                                     

                                   
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vmateriais_similares.material_similar,new{@class="txtcorposite"})</td>
                                   <td>@Html.DropDownListFor(a => a.vmateriais_similares.material_similar,material)</td>
                                  
                                   
                               </tr>
                                                           
                                               
                                                             
                                <tr>   
                                    @if ((ViewBag.Action == "InserirSimilar" || ViewBag.Action == "EditarSimilar") && Model.vmateriais_similares != null)
                                    {                                 
                                        <td><input type="image" class="btnIncluir" src="/Contents/Images/btnSalvar.png" value="submit"/></td>
                                        <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadSimilares" href="@Url.Action("Similar", "Materiais", new { id = Model.vmateriais.id })" role="button"><img src="/Contents/Images/btnCancelar.png" /></a></td>
                                    }    
                                </tr>
                             </table>
                            }  

    <table class="table">
        <tr>
            <td>
                <div id="divGridSimilar">
                    @{Html.RenderPartial("ListaSimilares",listasimilares);}
                </div>
            </td>
        </tr>
    </table>
               
                       