SisUnimed/Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisUnimed.Models;

namespace SisUnimed.Controllers
{
    [Serializable]
    public class FornecedorController : Controller
    {
        //
        // GET: /Fornecedor/
       
        public ActionResult Fornecedor()
        {
            if (Session["usuariologadoId"] != null)
            {
                using (UnimedEntities1 up = new UnimedEntities1())
                {
                    int usuario_id = int.Parse(Session["usuariologadoId"].ToString());
                    var resultado = up.usuario_permissao.Where(a => a.id_usuario.Equals(usuario_id)).FirstOrDefault();

                    ViewData["usuario_permissao"] = resultado;

                    // busca fornecedores na tabela
                    var fornecedor = from a in up.fornecedores
                                join b in up.usuarios on a.sisusuarioi equals b.id into g
                                join c in up.usuarios on a.sisusuarioa equals c.id into h
                                from x in g.DefaultIfEmpty()
                                from y in h.DefaultIfEmpty()
                                select new ListaFornecedor
                                {
                                    id = a.id,
                                    c_codigo = a.c_codigo,
                                    c_cnpj = a.c_cnpj,
                                    c_email_principal = a.c_email_principal,
                                    c_razao_social = a.c_razao_social,
                                    c_responsavel = a.c_responsavel,
                                    f_situacao = a.f_situacao == 1 ? "Ativo" : "Inativo",
                                    f_tipo_fornecedor = a.f_tipo_fornecedor == 1 ? "Distribuidor/Atacadista" : a.f_tipo_fornecedor == 2 ? "Fabricante" : a.f_tipo_fornecedor == 3 ? "Importador" : "Varegista",
                                    operadora = a.operadora1.c_nome,
                                    sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                    sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                    sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                    sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario)
                                };
                    ViewData["listafornecedor"] = fornecedor.ToList();

                    var operadora = from a in up.operadoras1
                                    select new ListaOperadora1
                                    {
                                        id = a.id,
                                        c_nome = a.c_nome
                                    };
                    
                    ViewData["listaoperadora"] = operadora.ToList();

                    var listabanco = from a in up.bancos
                                     select new ListaBanco
                                     {
                                         c_codigo = a.c_codigo,
                                         c_nome = a.c_descricao,
                                         id = a.id
                                     };
                    ViewData["listabanco"] = listabanco.ToList();

                    var listaestado = from a in up.estados
                                      select new ListaEstado
                                      {
                                          c_sigla = a.c_sigla,
                                          c_nome = a.c_nome,
                                          id = a.id
                                      };
                    ViewData["listaestado"] = listaestado.ToList();

                    // lista materiais
                    var listamateriais = from a in up.fornecedores_materiais
                                         join b in up.usuarios on a.sisusuarioi equals b.id into g
                                         join c in up.usuarios on a.sisusuarioa equals c.id into h
                                         from x in g.DefaultIfEmpty()
                                         from y in h.DefaultIfEmpty()
                                         where a.fornecedor == 0
                                         select new ListaFornecedorMateriais
                                         {
                                             id = a.id,
                                             material = a.materiai.c_nome_material,
                                             v_preco_ctnpm = a.v_preco_ctnpm,
                                             sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                             sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                             sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                             sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario),
                                             fornecedor = a.fornecedor
                                         };
                    ViewData["listamateriais"] = listamateriais.ToList();

                    var lstmaterial = from a in up.materiais
                                      select new ListaMaterial
                                      {
                                          c_nome_material = a.c_nome_material,
                                          id = a.id
                                      };
                    ViewData["lstmaterial"] = lstmaterial.ToList();

                    // lista banco
                    var listafornbanco = from a in up.fornecedores_bancos
                                         join b in up.usuarios on a.sisusuarioi equals b.id into g
                                         join c in up.usuarios on a.sisusuarioa equals c.id into h
                                         from x in g.DefaultIfEmpty()
                                         from y in h.DefaultIfEmpty()
                                         where a.fornecedor == 0
                                         select new ListaFornecedorBanco
                                         {
                                             id = a.id,
                                             banco = a.banco1.c_descricao,
                                             c_agencia = a.c_agencia,
                                             c_conta = a.c_conta,
                                             c_titular = a.c_titular,
                                             c_cidade = a.c_cidade,
                                             estado = a.estado1.c_sigla,
                                             sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                             sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                             sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                             sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario),
                                             fornecedor = a.fornecedor
                                         };
                    ViewData["listafornbanco"] = listafornbanco.ToList();

                    //Lista de Enderecos
                    var listaendereco = from a in up.fornecedores_enderecos
                                         join b in up.usuarios on a.sisusuarioi equals b.id into g
                                         join c in up.usuarios on a.sisusuarioa equals c.id into h
                                         from x in g.DefaultIfEmpty()
                                         from y in h.DefaultIfEmpty()
                                         where a.fornecedor == 0
                                         select new ListaEndereco
                                         {
                                             id = a.id,
                                             c_logradoro = a.c_logradouro,
                                             c_descricao = a.c_descricao,
                                             c_bairro = a.c_bairro,
                                             c_cep = a.c_cep,
                                             c_cidade = a.c_cidade,
                                             c_estado = a.estado1.c_sigla,
                                             c_numero = a.c_numero,
                                             sisdatai = a.sisdatai == null ? DateTime.Today : a.sisdatai,
                                             sisusuarioi = (x == null ? "Sem Dados" : x.nome_usuario),
                                             sisdataa = a.sisdataa == null ? DateTime.Today : a.sisdataa,
                                             sisusuarioa = (y == null ? "Sem Dados" : y.nome_usuario),
                                             fornecedor = a.fornecedor
                                         };
                    ViewData["listaendereco"] = listaendereco.ToList();

                    //lista telefone
                    var listatelefone = from a in up.fornecedores_telefones
                                        join b in up.usuarios on a.sisusuarioi equals b.id into g
                                        join c in up.usuarios on a.sisusuarioa equals c.id into h
                                        from x in g.DefaultIfEmpty()
                                        from y in h.DefaultIfEmpty()
                                        where a.fornecedor == 0
                                        select new ListaFornecedorTelefone
                                        {
                                            id = a.id,
                                            c_nome = a.c_nome,
                                            c_setor = a.c_setor,

SisUnimed/Views/Fornecedor/CadastroFornecedor.cshtml
@model SisUnimed.Models.vModelDetalheFornecedor
@{
    List<SelectListItem> listasituacao = new List<SelectListItem>();
    List<SelectListItem> listatipofornecedor = new List<SelectListItem>();
    IEnumerable<SisUnimed.Models.ListaOperadora1> listaoperadora = (IEnumerable<SisUnimed.Models.ListaOperadora1>)ViewData["listaoperadora"];    

    listasituacao.Add(new SelectListItem {
        Text = "Ativo",
        Value = "1"
    });
    listasituacao.Add(new SelectListItem {
        Text = "Inativo",
        Value = "2"
    });

    listatipofornecedor.Add(new SelectListItem {
        Text = "Distribuidor/Atacadista",
        Value = "1"
    });
    listatipofornecedor.Add(new SelectListItem {
        Text = "Fabricante",
        Value = "2"
    });
    listatipofornecedor.Add(new SelectListItem {
        Text = "Importador",
        Value = "3"
    });
    listatipofornecedor.Add(new SelectListItem {
        Text = "Varejista",
        Value = "4"
    });

    List<SelectListItem> operadoras = new List<SelectListItem>();
    foreach (var x in listaoperadora)
    {
        operadoras.Add(new SelectListItem {
            Text = x.c_nome,
            Value = x.id.ToString()
        }); 
    }    
    
}


               
                            @using (Ajax.BeginForm((string)ViewBag.Action,"Fornecedor",new AjaxOptions { HttpMethod="POST",InsertionMode = InsertionMode.Replace, UpdateTargetId="corposite" }, new{@id="formCadastro"}))
                            {
                                 @Html.AntiForgeryToken()
                                 @Html.ValidationSummary(true)
                                <table class="table">
                                 @if (@ViewBag.Message != null)
                                 {
                                     
                                     <tr>
                                         <td>
                                           
                                               @Html.Raw(ViewBag.Message)
                                            
                                         </td>
                                     </tr>
                                 }
                                <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.id)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.c_codigo)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.c_cnpj)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.c_razao_social)</font></td>
                                   

                                   
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vfornecedor.id,new{@class="txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedor.id, new { @size="10", @readonly = "true"})</td>
                                   <td>@Html.LabelFor(a => a.vfornecedor.c_codigo, new { @class="txtcorposite" })</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedor.c_codigo, new { @size="10", @style="text-transform: uppercase" })</td>
                                   <td>@Html.LabelFor(a => a.vfornecedor.c_cnpj, new{ @class = "txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedor.c_cnpj, new { value = Model.vfornecedor.c_cnpj })</td>
                                   <td>@Html.LabelFor(a => a.vfornecedor.c_razao_social,new {@class="txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedor.c_razao_social, new { @size = "30",@style="text-transform: uppercase"})</td>                                   
                                   
                               </tr>
                               <tr>
                                   <td></td>
                                    <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.c_responsavel)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.f_situacao)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.f_tipo_fornecedor)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.operadora)</font></td>
                                   

                               </tr>
                               <tr>
                                   <td>@Html.LabelFor(a => a.vfornecedor.c_responsavel, new {@class="txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedor.c_responsavel,new {@size="30",@style="text-transform: uppercase"})</td>
                                   <td>@Html.LabelFor(a => a.vfornecedor.f_situacao, new { @class="txtcorposite" })</td>
                                   <td>@Html.DropDownListFor(a => a.vfornecedor.f_situacao,listasituacao)</td>
                                   <td>@Html.LabelFor(a => a.vfornecedor.f_tipo_fornecedor,new { @class = "txtcorposite" })</td>
                                   <td>@Html.DropDownListFor(a => a.vfornecedor.f_tipo_fornecedor, listatipofornecedor)</td>
                                   <td>@Html.LabelFor(a => a.vfornecedor.operadora, new { @class = "txtcorposite" })</td>
                                   <td>@Html.DropDownListFor(a => a.vfornecedor.operadora,operadoras)</td>                                   
                               </tr>    
                               <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedor.c_email_principal)</font></td>
                                   <td></td>
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vfornecedor.c_email_principal,new {@class="txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedor.c_email_principal,new {@size="30",@style="text-transform: lowercase"})</td>
                               </tr>                  
                                                             
                                <tr>   
                                    @if (ViewBag.Action == "Inserir" || ViewBag.Action == "Editar")
                                    {                                 
                                        <td><input type="image" class="btnIncluir" src="/Contents/Images/btnSalvar.png" value="submit"/></td>
                                        <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#corposite" href="@Url.Action("Fornecedor","Fornecedor")" role="button"><img src="/Contents/Images/btnCancelar.png" /></a></td>
                                    }    
                                </tr>
                             </table>
                            }  

    <script>
        $(document).ready(function () {
            $("#vfornecedor_c_cnpj").inputmask("mask", { "mask": "99.999.999/9999-99" });
        });
    </script>
               
                       

SisUnimed/Views/Fornecedor/FonecedorBanco.cshtml
@model SisUnimed.Models.vModelDetalheFornecedor
@{
    
    IEnumerable<SisUnimed.Models.ListaBanco> listabanco = (IEnumerable<SisUnimed.Models.ListaBanco>)ViewData["listabanco"];
    IEnumerable<SisUnimed.Models.ListaEstado> listaestado = (IEnumerable<SisUnimed.Models.ListaEstado>)ViewData["listaestado"];
    IEnumerable<SisUnimed.Models.ListaFornecedorBanco> listafornbanco = (IEnumerable<SisUnimed.Models.ListaFornecedorBanco>)ViewData["listafornbanco"];   
       
    List<SelectListItem> banco = new List<SelectListItem>();
    foreach (var x in listabanco)
    {
        banco.Add(new SelectListItem {
            Text = x.c_nome + '-' + x.c_codigo,
            Value = x.id.ToString()
        }); 
    }

    List<SelectListItem> estado = new List<SelectListItem>();
    foreach (var x in listaestado)
    {
        estado.Add(new SelectListItem { 
            Text = x.c_sigla,
            Value = x.id.ToString()
        });
    }   
    
}
<table class="table">
    <tr>
        @if (Model.vfornecedor.id > 0)
        {
            <td width="65px"><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadBanco" href="@Url.Action("IncluirBanco", "Fornecedor", new { id = Model.vfornecedor.id })" role="button"><img src="/Contents/Images/btnAdd.png" /></a></td>
        }
        @if (Model.vfornecedores_bancos != null && (Model.vfornecedores_bancos.id) > 0)
        {
            <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadBanco" href="@Url.Action("DeleteBanco","Fornecedor",new {id_banco = Model.vfornecedores_bancos.id, id = Model.vfornecedor.id })" role="button"><img src="/Contents/Images/btnExcluir.png" /></a></td>
        }
    </tr>
</table>


               
                            @using (Ajax.BeginForm((string)ViewBag.Action,"Fornecedor",new AjaxOptions { HttpMethod="POST",InsertionMode = InsertionMode.Replace, UpdateTargetId="cadBanco" }, new{@id="formCadastro"}))
                            {
                                 @Html.AntiForgeryToken()
                                 @Html.ValidationSummary(true)
                                @Html.HiddenFor(a => a.vfornecedores_bancos.id)
                                @Html.HiddenFor(a => a.vfornecedores_bancos.fornecedor)
                                <table class="table">
                                 @if (@ViewBag.Message != null)
                                 {
                                     
                                     <tr>
                                         <td>
                                           
                                               @Html.Raw(ViewBag.Message)
                                            
                                         </td>
                                     </tr>
                                 }
                                <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_bancos.banco)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_bancos.c_agencia)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_bancos.c_conta)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_bancos.c_titular)</font></td>
                                   

                                   
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vfornecedores_bancos.banco,new{@class="txtcorposite"})</td>
                                   <td>@Html.DropDownListFor(a => a.vfornecedores_bancos.banco,banco)</td>
                                   <td>@Html.LabelFor(a => a.vfornecedores_bancos.c_agencia, new { @class="txtcorposite" })</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedores_bancos.c_agencia, new { @size="10", @style="text-transform: uppercase" })</td>
                                   <td>@Html.LabelFor(a => a.vfornecedores_bancos.c_conta, new{ @class = "txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedores_bancos.c_conta, new { @size = "15", @style="text-transform: uppercase" })</td>
                                   <td>@Html.LabelFor(a => a.vfornecedores_bancos.c_titular,new {@class="txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedores_bancos.c_titular, new { @size = "30",@style="text-transform: uppercase"})</td>                                   
                                   
                               </tr>
                               <tr>
                                   <td></td>
                                    <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_bancos.c_cidade)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_bancos.estado)</font></td>                                 
                                   

                               </tr>
                               <tr>
                                   <td>@Html.LabelFor(a => a.vfornecedores_bancos.c_cidade, new {@class="txtcorposite"})</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedores_bancos.c_cidade,new {@size="30",@style="text-transform: uppercase"})</td>
                                   <td>@Html.LabelFor(a => a.vfornecedores_bancos.estado, new { @class="txtcorposite" })</td>
                                   <td>@Html.DropDownListFor(a => a.vfornecedores_bancos.estado,estado)</td>                                                                     
                               </tr> 
                               
                                               
                                                             
                                <tr>   
                                    @if ((ViewBag.Action == "InserirBanco" || ViewBag.Action == "EditarBanco") && Model.vfornecedor != null)
                                    {                                 
                                        <td><input type="image" class="btnIncluir" src="/Contents/Images/btnSalvar.png" value="submit"/></td>
                                        <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadBanco" href="@Url.Action("Banco", "Fornecedor", new { id = Model.vfornecedor.id })" role="button"><img src="/Contents/Images/btnCancelar.png" /></a></td>
                                    }    
                                </tr>
                             </table>
                            }  

    <table class="table">
        <tr>
            <td>
                <div id="divGridBanco">
                    @{Html.RenderPartial("ListaFornBanco",listafornbanco);}
                </div>
            </td>
        </tr>
    </table>
               
                       

SisUnimed/Views/Fornecedor/FornecedorMateriais.cshtml
@model SisUnimed.Models.vModelDetalheFornecedor
@{
    
    IEnumerable<SisUnimed.Models.ListaFornecedorMateriais> listamateriais = (IEnumerable<SisUnimed.Models.ListaFornecedorMateriais>)ViewData["listamateriais"];
    IEnumerable<SisUnimed.Models.ListaMaterial> lstmaterial = (IEnumerable<SisUnimed.Models.ListaMaterial>)ViewData["lstmaterial"];

    List<SelectListItem> material = new List<SelectListItem>();
    
    foreach (var x in lstmaterial)
    {
        material.Add(new SelectListItem { 
            Text = x.c_nome_material,
            Value = x.id.ToString()
        });   
    };
       
   
    
}
<table class="table">
    <tr>
        @if (Model.vfornecedor.id > 0)
        {
            <td width="65px"><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadMateriais" href="@Url.Action("IncluirMaterial", "Fornecedor", new { id = Model.vfornecedor.id })" role="button"><img src="/Contents/Images/btnAdd.png" /></a></td>
        }
        @if (Model.vfornecedores_materiais != null && (Model.vfornecedores_materiais.id) > 0)
        {
            <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadMateriais" href="@Url.Action("DeleteMaterial","Fornecedor",new {id_mat = Model.vfornecedores_materiais.id, id = Model.vfornecedor.id })" role="button"><img src="/Contents/Images/btnExcluir.png" /></a></td>
        }
    </tr>
</table>


               
                            @using (Ajax.BeginForm((string)ViewBag.Action,"Fornecedor",new AjaxOptions { HttpMethod="POST",InsertionMode = InsertionMode.Replace, UpdateTargetId="cadMateriais" }, new{@id="formCadastro"}))
                            {
                                 @Html.AntiForgeryToken()
                                 @Html.ValidationSummary(true)
                                @Html.HiddenFor(a => a.vfornecedores_materiais.id)
                                @Html.HiddenFor(a => a.vfornecedores_materiais.fornecedor)
                                <table class="table">
                                 @if (@ViewBag.Message != null)
                                 {
                                     
                                     <tr>
                                         <td>
                                           
                                               @Html.Raw(ViewBag.Message)
                                            
                                         </td>
                                     </tr>
                                 }
                                <tr>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_materiais.material)</font></td>
                                   <td></td>
                                   <td><font style="color: red;text-align:right;font-size:11px">@Html.ValidationMessageFor(a => a.vfornecedores_materiais.v_preco_ctnpm)</font></td>
                                   <td></td>
                                   <td></td>
                                   <td></td>
                                   <td></td>
                                   

                                   
                               </tr> 
                               <tr>
                                   <td>@Html.LabelFor(a => a.vfornecedores_materiais.material,new{@class="txtcorposite"})</td>
                                   <td>@Html.DropDownListFor(a => a.vfornecedores_materiais.material,material)</td>
                                   <td>@Html.LabelFor(a => a.vfornecedores_materiais.v_preco_ctnpm, new { @class="txtcorposite" })</td>
                                   <td>@Html.TextBoxFor(a => a.vfornecedores_materiais.v_preco_ctnpm,new {@size="15"})</td>
                                   <td></td>
                                   <td></td>
                                   <td></td>
                                   <td></td>                                   
                                   
                               </tr>
                                                                                           
                                <tr>   
                                    @if ((ViewBag.Action == "InserirMaterial" || ViewBag.Action == "EditarMaterial") && Model.vfornecedor != null)
                                    {                                 
                                        <td><input type="image" class="btnIncluir" src="/Contents/Images/btnSalvar.png" value="submit"/></td>
                                        <td><a class="btnIncluir" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#cadMateriais" href="@Url.Action("Materiais", "Fornecedor", new { id = Model.vfornecedor.id })" role="button"><img src="/Contents/Images/btnCancelar.png" /></a></td>
                                    }    
                                </tr>
                             </table>
                            }  

    <table class="table">
        <tr>
            <td>
                <div id="divGridMaterial">
                    @{Html.RenderPartial("ListaFornMateriais",listamateriais);}
                </div>
            </td>
        </tr>
    </table>
 <script>
        $(document).ready(function () {
            $("#vfornecedores_materiais_v_preco_ctnpm").inputmask("currency", { "prefix": "", "groupSeparator": ".", "radixPoint": "," });
        });
    </script>
               
                       